### ISSUE TITLE
[request] Move torrent file after it's been labeled, not only after it's been downladed

### ISSUE THREAD

**Issue by vasamaximov** [ratanakvlun/deluge-labelplus#12] opened 2016-02-13 12:14 UTC
could you make the subj possible, please? Many thanks!

**Comment by werkkrew** [comment] 2016-03-12 20:59
I would also love this functionality, although my use case might not work since the LabelPlus plugin seems to not behave like the built in label plugin, e.g. tools like couch potato can't seem to assign label plus labels to torrents

**Comment by ratanakvlun** [comment] 2016-05-01 13:52
This is actually the intended behavior when the 'move on torrent label change' option is set. Do you have this option set?

**Comment by ratanakvlun** [comment] 2016-08-28 18:03
Closing because this is already in the plugin.

**Closed by ratanakvlun** 2016-08-28 18:03 UTC
