### ISSUE TITLE
[Request (Unintentional?)] Not to force the LabelPlus label reset when changing Deluge normal label on a torrent

### ISSUE THREAD

**Issue by Drakonas** [ratanakvlun/deluge-labelplus#14] opened 2016-05-01 05:43 UTC
When changing the normal label for a torrent (Deluge integrated label system), LabelPlus (Or is this Deluge doing this?) resets the LabelPlus label to blank. Can there be an option to not do this? Quite frankly I don't see why anyone would want this. I love LabelPlus for my desktop use, but I need Deluge labels for seeing categories on my Android TransDroid client (which obviously doesn't support LabelPlus)

**Comment by ratanakvlun** [comment] 2016-05-01 13:38
LabelPlus uses a separate data store for its label mappings, so changing the Deluge label shouldn't have any effects on the LabelPlus label. The reverse is also true, setting the LabelPlus label shouldn't affect the Deluge label. What method are you using to change labels?

**Comment by Drakonas** [comment] 2016-05-01 19:36
I am using the GTK UI on Windows (1.3.12) to connect to a remote 1.3.11 server. Both the server and the client have the latest LabelPlus plugin (0.3.2.2). If I have a LabelPlus label set on a torrent, but not a Deluge label, if I simply right-click the torrent -> Label -> choose any label, it removes the LabelPlus label.

**Comment by ratanakvlun** [comment] 2016-05-01 21:32
Confirmed. It looks like this has to do with Deluge labels being made into a LabelPlus autolabel criteria. LabelPlus needs to know when a Deluge label changes so that it can do an autolabel based on it, so it hooks into the Deluge label plugin and some logic there is where this is producing this behavior.

**Comment by getzze** [comment] 2016-05-31 14:02
Related to this, is there a way to assign a normal label using the rules of labelplus?
In transdroid, only the normal labels appear, it would be great if they could be assigned automatically using labelplus.

**Comment by Drakonas** [comment] 2016-05-31 21:51
That would be a great idea, but I think that LabelPlus, as well as most plugins, have to run both client-side and server side. The plugin isn't actually loaded and running unless you have the daemon open and are changing things from it, which the Deluge Windows app connects to. Not only that, but Transdroid and similar apps connect to the WebUI, which LabelPlus doesn't run in.

**Comment by ratanakvlun** [comment] 2016-08-27 19:16
Fixed in commit 29bc0ab7.

If you are still interested in LabelPlus setting Deluge labels, please open another issue.

**Closed by ratanakvlun** 2016-08-27 19:16 UTC
